### ISSUE TITLE
cool project

### ISSUE THREAD

**Issue by wyattzheng** [shift-reality/php-crypto#1]
are you going to build a php-miner of Monero coin?
they are all algos that CryptoNote mentioned

thanks to your contributions!

**Comment by wyattzheng** [comment]
i can't understand why the implements of algos need extensions.it should be pure php like this project

**Comment by shift-reality** [comment]
Yes, i tried to implement cryptonight algo... But without direct access to machine instructions (like intel 128 bit integers) is very slow.. Extensions is written on C language and muuuuch faster than pure PHP.
And CN also require fast random memory r/w...-I can't found work-around of this problem....

**Comment by shift-reality** [comment]
Final variant of php-miner produce 1 hash per 15-30 seconds)) Incredible speed

**Comment by wyattzheng** [comment]
that is too slow,and that is why CN algo can prevent ASIC,fast memory speed is needed.have you try running phpminer at local machine

**Comment by shift-reality** [comment]
Yes, i running performance tests using php-cli (machine is 8-core AMD processor, 8GB RAM, debian 9)
so slow...

Maybe need look to /dev/shm or some other fast memory, but this to invoke syscall to read/write and probably increase mem access time... No solution

**Comment by wyattzheng** [comment]
that is a bad news.php 7.0 is 2 times faster than php5.6. hope php can provide cpu cache mem interface,or really no solution.i will use your algo implements to build a phpminer to start my tests

**Comment by ZhyMC** [comment]
i think you know Pocketmine-MP which is also written in PHP,it work well

**Comment by wyattzheng** [comment]
i noticed that CryptoNight for NodeJs works well.have you read coinhive source codes? 3H/s it can reach in my PC.Theoretically,php should work as well as nodejs

**Comment by shift-reality** [comment]
i test on php 7.2 with opcache. You can use code as you want and anywhere...) Please tell me you result stat when all is done

>>>**Theoretically**,php should work as well as nodejs
:)

**Comment by wyattzheng** [comment]
all right,thanks

**Comment by wyattzheng** [comment]
i start perf test of these codes,i found that oaes_mix_cols cause too much times,when i disable this,the efficiency increase to 3 times higher than before

**Comment by wyattzheng** [comment]
also,   'global' is toooooooooooooooo slow

**Comment by wyattzheng** [comment]
those array with many default value spend much time,i think they can combine into a string,then substring them

**Comment by shift-reality** [comment]
I think about this... And PHP can apply bitwise operations to string like XOR
so, faster XOR 2 strings fully than 2 arrays of N elements
because ^ is operator, and perform 1 operation to any-length string
"hello"^"12345"
equals to five ops:
h^1
e^2
l^3
...

**Comment by shift-reality** [comment]
also need to unroll all loop, if's... etc

**Comment by shift-reality** [comment]
oaes is totally copied from C lang and adopted to PHP lang.. without any changes

About coinhive:
-In browser used WebAssembly
-nodejs load external dll/so with miner (i believe)

**Comment by wyattzheng** [comment]
30seconds a hash is too slow,i think there are still spaces to optimize the codes.although it can not achieve the speed like WebAssembly.

**Comment by shift-reality** [comment]
There is another problem, cryptonight use AESENC x86 instruction:
https://www.felixcloutier.com/x86/AESENC.html
But PHP don't obtain this feature never

**Comment by shift-reality** [comment]
I thing general problem is in AESENC.. because extra hashes is supplimental and take less of 0.01% of all time, non-critical

**Comment by wyattzheng** [comment]
right,One Round Aes spends almost full of time

**Comment by shift-reality** [comment]
Any working solution? maybe need check built-in extensions? Like bcmath?

**Comment by wyattzheng** [comment]
using extensions rathan than writing whole the CN algo into a extension.I'm trying  as much as possible to optimize the codes without a extension so i can upload this to freehost to earn XMR-coin

**Comment by wyattzheng** [comment]
hey man,look this https://github.com/ZhyMC/phpminer

**Comment by wyattzheng** [comment]
i code mine.php and found a solution of SubAndShiftAndMixAddRoundInPlace,this is very fast and i have verified it's correct.but i haven't finish mine.php, hope tonight i can finish it

**Comment by shift-reality** [comment]
Good
But where you found cryptonight file ? I missed and not uploaded to github *maybe*)

**Comment by wyattzheng** [comment]
i code it by myself spend over 20 hours.your blake256.php work in 64bit system caught some problems,so i have to fix it

**Comment by shift-reality** [comment]
how much hashes now?

**Comment by wyattzheng** [comment]
20~30secs a hash just like yours,but i prepare to optimize codes when i finish the phpminer

**Comment by wyattzheng** [comment]
i gonna use microtimes to check Timings.See which part is most slow and try to do a change

**Comment by shift-reality** [comment]
i uploaded cn.php may it's help you, don't know

**Comment by wyattzheng** [comment]
i almost finish the cn.php myself, hahaha

**Comment by shift-reality** [comment]
what is problem with blake256?

**Comment by shift-reality** [comment]
maybe don't upload updates to project until it's ready and final stats available?)

**Comment by wyattzheng** [comment]
it's about PHP_INT_MAX, php allow a number > 2147483647 when environment is 64bit,but somethings we need integer overflow

**Comment by wyattzheng** [comment]
try to make it 0.1H/s,i think it's possible,and over this speed the project start to be a kind of useful,

**Comment by shift-reality** [comment]
ok

You debug hash func's, and after i finalize it - write usefull library,make code good
write unit-tests for hash fn-s... etc
and you add this as composer dep
:)

**Comment by shift-reality** [comment]
so i write crypto-library, you write phpminer
Good

**Comment by wyattzheng** [comment]
that's nice

**Comment by wyattzheng** [comment]
i fixed blake256 and work well in 64bit system.and CN is done!
watch my codes at https://github.com/ZhyMc/phpminer

**Comment by wyattzheng** [comment]
finally!!

**Comment by shift-reality** [comment]
it's worked now? how much h/s?

**Comment by wyattzheng** [comment]
i just finished it.and the next step is to optimize it. (1/20 )h/s

**Comment by shift-reality** [comment]
CN hash is correct?

**Comment by shift-reality** [comment]
what is function trans($nb) actually doing? I have no idea what can broke b256 on 64 bit windows platform (i tested on PHP 7.2 for AMD x86_64) and blake hashes is fine calculated

**Comment by wyattzheng** [comment]
but in my computer it calculated wrong results.trans() make 64int overflow like  32int

**Comment by shift-reality** [comment]
ok, later i create test cases for blake with more data&hash pairs and we can check this behavior

Please, after it's ready, create inplace(remove function call) code for SubAndShiftAndMixAddRoundInPlace, xor_blocks .... etc
This increase calc speed in 3-5 times, i tested

**Comment by wyattzheng** [comment]
wow 3-5times ,that makes me feel there are lots of spaces to optimze

**Comment by wyattzheng** [comment]
i'm working on stratum protocol,it is exciting to me

**Comment by shift-reality** [comment]
i suggest to not use stratum.. Use long poll instead.
Because it's easiest way and not require extra threads for IO.

Miner arch should be like this:
1 master process-communicate with minepoll and receiver tasks
N slave processes compute hashes
+This allow to stop process if hash is already mined by somebody other
+Not required thread model

IPC can be implemented used named pipe

**Comment by wyattzheng** [comment]
just like what you said,i learn the theory of pool .You can see that my phpminerBridge.js and phpminer.php

**Comment by shift-reality** [comment]
yes, i seen latest u'r activity

**Comment by wyattzheng** [comment]
i run the perfm tests,and i found many many many perfm problems we can avoid.
for example, intval() is super slow, 600% slower than (int), and it is called very often.
and many details waiting us to work with.i made 40seconds a hash up to 25seconds a hash,and keep trying

**Comment by shift-reality** [comment]
You can await until i upload new lib with 4 hash functions?
blake(your last variant) jh gro skein
Now it's complete 50/50...
So, other parts like oaes and CN goes to your phpminer project and purged from lib.
u64 class goes to lib into 'utils' namespace.

I think intval is fn call + new zval created, where (int) is just syntax cast and same zendval used

**Comment by wyattzheng** [comment]
sure,we work for more effiency,i desire new library to include.You know a lot about the core of php like zval

**Comment by wyattzheng** [comment]
blake jh gro skein 
they are called one time ,and cost few times

**Comment by shift-reality** [comment]
Yes, we place it into library
And i help you with main code

**Comment by wyattzheng** [comment]
ok

**Comment by shift-reality** [comment]
skein-256-256 or skein-512-256 used in CN?

**Comment by wyattzheng** [comment]
don't know,https://cryptonote.org/cns/cns008.txt said it's skein-256

**Comment by shift-reality** [comment]
can you research about this problem? I have no ideas
Implementation is diff and hashes too

**Comment by shift-reality** [comment]
Currenty is skein 512-256, i can implement 256-256

**Comment by wyattzheng** [comment]
skein 512-256 is used for what.i think it's difficult for me ,so i use your algo libs

**Comment by shift-reality** [comment]
Ok, i uploaded new lib into new branch.

Tests fine (run test.php on your's machine to compare):
test JH256#0 is: OK
test BLAKE256#1 is: OK
test BLAKE256#2 is: OK
test BLAKE256#3 is: OK
test BLAKE256#4 is: OK
test BLAKE256#5 is: OK
test BLAKE256#6 is: OK
test BLAKE256#7 is: OK
test BLAKE256#8 is: OK
test GROESTL256#9 is: OK
test GROESTL256#10 is: OK
test GROESTL256#11 is: OK
test GROESTL256#12 is: OK
test SKEIN256#13 is: OK
test SKEIN256#14 is: OK
test SKEIN256#15 is: OK

You can modify file fixtures.json to add some test cases(JH256 has only one test). Skein 512-256 already implemented.
Usage is like that:
`$hash = Hasher::doHash($algo, InputDataSupplier::forHex($dataHex));`
Please Look to file InputDataSupplier and IHash to more info (input/output is actually set from hex/binary string and bytes array)

Final code is:
replace from:
`//√
switch($chosen){
	case 0:
	echo "blake256\n";
	$ret=blake256($data_ret);break;
	case 1:
	echo "groestl256\n";
	$ret=groestl256($data_ret);break;
	case 2:
	echo "jh\n";
	$ret=jh($data_ret);break;
	case 3:
	echo "skein\n";
	$ret=skein($data_ret);break;
}`
TO:
`$hashes = ['BLAKE256','GROESTL256','JH256','SKEIN256'];
$algo = $hashes[$chosen];
echo "$algo\n";
$ret = Hasher::doHash($algo, InputDataSupplier::forByteArray($inputDataArray))->byteArray();`

**Comment by wyattzheng** [comment]
nice!you pack them into one lib!i will run the test.php and follow this

**Comment by wyattzheng** [comment]
don't find a test.php in your project folder, can you upload yours?

**Comment by shift-reality** [comment]
https://github.com/shift-reality/php-crypto/tree/newlib
composer.json:

`{
    "name": "shift196/php-project3-example",
    "description": "Description of project PhpProject3-example.",
    "authors": [
        {
            "name": "bogdan",
            "email": "shift196@yandex.ru"
        }
    ],
    "repositories": [
        {
            "url": "https://github.com/shift-reality/php-crypto.git",
            "type": "git",
            "reference": "newlib"
        }
    ],
    "require": {
        "shift196/lib-akash": "dev-newlib"
    }
}
`

**Comment by wyattzheng** [comment]
ok,they are in new branch

**Comment by shift-reality** [comment]
I submit new stable version, so you can use 1.0.*

**Comment by shift-reality** [comment]
Useful feature: **Hasher::registerAlgo**, can be used for register KECCAK and cryptonight into lib. So usage is become easy..
Like that:
Hasher::registerAlgo('CRYPTONIGHT', new CryptonightImpl());
CryptonightImpl should implement interface IHashFunction

**Comment by wyattzheng** [comment]
test JH256#0 is: OK
test BLAKE256#1 is: OK
test BLAKE256#2 is: OK
test BLAKE256#3 is: OK
test BLAKE256#4 is: OK
test BLAKE256#5 is: OK
test BLAKE256#6 is: OK
test BLAKE256#7 is: OK
test BLAKE256#8 is: OK
test GROESTL256#9 is: OK
test GROESTL256#10 is: OK
test GROESTL256#11 is: OK
test GROESTL256#12 is: OK
test SKEIN256#13 is: OK
test SKEIN256#14 is: OK
test SKEIN256#15 is: OK

work well

**Comment by wyattzheng** [comment]
You made this become structured.More algos!

**Comment by shift-reality** [comment]
I think need add adapter to openssl digest algos if it's available, for biggest support list

**Comment by wyattzheng** [comment]
Hahaha,you are good at and interested in implementing algos in pure PHP.That makes those who made algos-extensions embarrassed.If you add more COMPLEX algos in pure PHP,i think this project will be famous.More people like to import it

**Comment by shift-reality** [comment]
$longstate=new splFixedArray(2097152);//Thanks to god,we have this;

Is that really faster than array?

**Comment by wyattzheng** [comment]
really,about 10% faster,but it cost half memory usage. i have to use this

**Comment by wyattzheng** [comment]
it can replace ARRAY immediately without changing any code

**Comment by wyattzheng** [comment]
default php settings included 30 seconds running time limit and 64M memory limit .I try my best finally the limits are both unreachable

**Comment by wyattzheng** [comment]
https://github.com/deepwn/phpminer 
Added phpcryptolib !

**Comment by shift-reality** [comment]
any problem with keccak or cryptonight?

**Comment by wyattzheng** [comment]
when you pack keccak into Hash class,and i use it.CryptoNight.php it's written by me,and i want keep this.How fast your cn.php behave?

**Comment by shift-reality** [comment]
Oaes and CN is 100% part of phpminer, but
i not sure about keccak functions.. If i add it into lib, only 1 method from interface IHashFunction is available-doHash.. But in CN used keccakf and keccak1600...

Is keccak called one time as other functions or should be optimized?

I not sure about my cn.php) probably extremely slow

**Comment by shift-reality** [comment]
Why you changed ___encodeLELong to ___encodeBELong?

**Comment by shift-reality** [comment]
test JH256#0 is: OK
test BLAKE256#1 is: OK
test BLAKE256#2 is: OK
test BLAKE256#3 is: OK
test BLAKE256#4 is: OK
test BLAKE256#5 is: OK
test BLAKE256#6 is: OK
test BLAKE256#7 is: OK
test BLAKE256#8 is: OK
test GROESTL256#9 is: OK
test GROESTL256#10 is: OK
test GROESTL256#11 is: OK
test GROESTL256#12 is: OK
test SKEIN256#13 is: OK
test SKEIN256#14 is: OK
test SKEIN256#15 is: OK
test KECCAK256#16 is: OK
test KECCAK256#17 is: OK
test KECCAK256#18 is: OK

Download 1.0.1 version for keccak, usage is:
`$keccak = Keccak::getInstance(); 

//round-function:
$keccak->keccakf(array $state, int $rounds);

//256-bit hash:
$keccak->keccak1600(array $inputData, array &$hash);
or
$hash=$keccak->doHash($inputData);
or
$hashObject = Hasher::doHash('KECCAK256', ...);`

**Comment by ZhyMC** [comment]
i spent lots of time to search out the BOTTLENECK of performance。And now i have a valued report.Bottleneck is DEFINITELY NOT about Math Calculating.

new o_u64(a,b);
this cost so much time;You can run this line 500000 times to test it running in LOOPS.This is one of MAIN reason why being so low efficiency.

Why I can sure that this is not because of Math Calculating,i was running many tests about Math Calculating like XOR bitShift,it cost little even in 500000 times.

How to solve this problem about "new o_u64(a,b);"???, new a PHP Class cost too much,and every time we do a bit-calc like ShiftRight,it will NEW a new o_64 to as a return value.

**Comment by shift-reality** [comment]
> i spent lots of time to search out the BOTTLENECK of performance。And now i have a valued >report.Bottleneck is DEFINITELY NOT about Math Calculating.

>new o_u64(a,b);
>this cost so much time;You can run this line 500000 times to test it running in LOOPS.This is one of >MAIN reason why being so low efficiency.

>Why I can sure that this is not because of Math Calculating,i was running many tests about Math >Calculating like XOR bitShift,it cost little even in 500000 times.

>How to solve this problem about "new o_u64(a,b);"???, new a PHP Class cost too much,and every >time we do a bit-calc like ShiftRight,it will NEW a new o_64 to as a return value.

Look to Object Pool pattern, and create Uint64Poll class with methods:
-getObject -returnObject
This allow to reuse same object and not need to create new instances every time

**Comment by shift-reality** [comment]
or just make all o_u64 methods static and add zero-arg: `array $data`
where 0 index = hi, 1 = lo like` list($hi,$lo)=$data;`
so used new array with 2 elements instead of object creation
or just use 8-bytes binary string (need alot of changes)

**Comment by shift-reality** [comment]
pool it's right way

**Comment by shift-reality** [comment]
I create pool for that, please await about 10 min

**Comment by shift-reality** [comment]
https://github.com/shift-reality/php-crypto/releases

**Comment by shift-reality** [comment]
object instantiation is hidden into getObject method
So when u64 object not needed more you should call `UInt64Poll::returnObject($obj)`

**Comment by shift-reality** [comment]
If both operands for the &, | and ^ operators are strings, then the operation will be performed on the ASCII values of the characters that make up the strings and the result will be a string. In all other cases, both operands will be converted to integers and the result will be an integer.

If the operand for the ~ operator is a string, the operation will be performed on the ASCII values of the characters that make up the string and the result will be a string, otherwise the operand and the result will be treated as integers.

**We need implement this, so u64 class become to 8-byte string**
XOR easiest
$str0^$str1
Faster that manipulate each byte in N times, i checked.. where N is count of iters(array elements)

**Comment by shift-reality** [comment]
UInt64String works fine
Need profile performance of this

**Comment by wyattzheng** [comment]
oh,i am coding to make mul_sum_xor_dst() and xor_blocks() into an extension.I found that Binary ("8bytes string") worked well when passing data into it.So,it's neccessary to implement UInt64String class.PHPMiner will use extension_loaded to detect if extension loaded.If not,using UInt64String to calculate.That is perfect solution I think

**Comment by wyattzheng** [comment]
wow , you had implemented That !!!!!!
I download this utils library right now

**Comment by shift-reality** [comment]
ext is not pure php and not work on freehost

**Comment by wyattzheng** [comment]
it's hard believe that the price of my host is 0.1$/1month,and support php.ini and extension.And pure PHP is IMPOSSIBLE to earn XMR

**Comment by shift-reality** [comment]
what you think about UInt64String?

**Comment by shift-reality** [comment]
i read some articles of subject -object pooling
Statistics said that method will increase performance +4000% in PHP with object pool size = 1024objects

**Comment by wyattzheng** [comment]
lots of functions need to change into a strange codes like SubAndShiftAndMixAddRound(),.I am trying to use this to rewrite my cryptonight().Your statistics data is gratifying

**Comment by wyattzheng** [comment]
almost all the codes need to rewrite if use UInt64String,so hard

**Comment by shift-reality** [comment]
don't rewrite code, use pooled u64 version instead
but not forget return objects to pool
